# Generated by Django 3.1.2 on 2020-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=4)),
                ('sex', models.IntegerField(choices=[(1, 'man'), (2, 'women')])),
            ],
            options={
                'db_table': 'tb_users',
            },
        ),
    ]
