# Generated by Django 3.1.2 on 2020-11-15 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo')),
            ],
            options={
                'db_table': 'tb_users_desc',
            },
        ),
    ]
