# Generated by Django 3.1.2 on 2020-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugtalks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalks',
            name='name',
            field=models.CharField(default='debugtalk.py', help_text='debugtalk文件名称', max_length=200, verbose_name='debugtalk文件名称'),
        ),
    ]
